AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/KeywordArgumentsMerging:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false
