# frozen_string_literal: true

require 'spec_helper'

RSpec.describe "Nested Includes" do
  let(:product_class) do
    Class.new do
      include ActiveShopifyGraphQL::Base
      graphql_type "Product"
      attribute :id
      attribute :title
    end
  end

  let(:variant_class) do
    Class.new do
      include ActiveShopifyGraphQL::Base
      graphql_type "ProductVariant"
      attribute :id
      attribute :sku

      has_many_connected :product, class_name: "Product", query_name: "product"
    end
  end

  let(:line_item_class) do
    Class.new do
      include ActiveShopifyGraphQL::Base
      graphql_type "LineItem"
      attribute :id
      attribute :quantity

      has_one_connected :variant, class_name: "ProductVariant", query_name: "variant"
    end
  end

  let(:order_class) do
    Class.new do
      include ActiveShopifyGraphQL::Base
      graphql_type "Order"
      attribute :id
      attribute :name

      has_many_connected :line_items, class_name: "LineItem", query_name: "lineItems", default_arguments: { first: 50 }
    end
  end

  before do
    stub_const("Product", product_class)
    stub_const("ProductVariant", variant_class)
    stub_const("LineItem", line_item_class)
    stub_const("Order", order_class)
  end

  it "generates correct GraphQL query for nested includes" do
    loader = Order.includes(line_items: { variant: :product }).default_loader

    # We can inspect the query generated by the loader
    query = loader.graphql_query
    expect(query).to include("lineItems(first: 50) {")
    expect(query).to include("edges {")
    expect(query).to include("node {")
    expect(query).to include("variant {")
    expect(query).to include("product {")
  end

  it "extracts nested data correctly" do
    loader = Order.includes(line_items: { variant: :product }).default_loader

    response_data = {
      "data" => {
        "order" => {
          "id" => "gid://shopify/Order/1",
          "lineItems" => {
            "edges" => [
              {
                "node" => {
                  "id" => "gid://shopify/LineItem/1",
                  "variant" => {
                    "id" => "gid://shopify/ProductVariant/1",
                    "product" => {
                      "edges" => [
                        {
                          "node" => {
                            "id" => "gid://shopify/Product/1",
                            "title" => "Test Product"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      }
    }

    connection_data = ActiveShopifyGraphQL::ResponseMapper.new(
      graphql_type: loader.graphql_type,
      loader_class: loader.class,
      defined_attributes: loader.defined_attributes,
      model_class: loader.instance_variable_get(:@model_class),
      included_connections: loader.instance_variable_get(:@included_connections)
    ).extract_connection_data(response_data)
    line_items = connection_data[:line_items]
    expect(line_items.size).to eq(1)
    line_item = line_items.first
    expect(line_item).to be_a(LineItem)

    variant = line_item.variant
    expect(variant).to be_a(ProductVariant)

    products = variant.product
    expect(products.size).to eq(1)
    product = products.first
    expect(product).to be_a(Product)
    expect(product.title).to eq("Test Product")
  end
end
